RRIncData_Imported_Loot = {}
RRIncData_Imported_LootTimestamp = "2021-01-25 19:15:19"

RRIncData_Imported_Loot['Anubisath Warhammer']={{name="Nothagnus", ranking=53},{name="Yallfolx", ranking=45}}
RRIncData_Imported_Loot['Garb of Royal Ascension']={{name="Adamnnan", ranking=40}}
RRIncData_Imported_Loot['Ritssyn\'s Ring of Chaos']={{name="Jolina", ranking=49},{name="Sujjilad", ranking=39},{name="Drstomplol", ranking=38}}
RRIncData_Imported_Loot['Shard of the Fallen Star']={{name="Derpa", ranking=47},{name="Petarus", ranking=42}}
RRIncData_Imported_Loot['Imperial Qiraji Armaments']={{name="Exeles", ranking=61},{name="Yallfolx", ranking=50},{name="Pudde", ranking=47},{name="Cakey", ranking=43},{name="Hardcoore", ranking=43}}
RRIncData_Imported_Loot['Imperial Qiraji Regalia']={{name="Pug", ranking=53},{name="Greenglare", ranking=52},{name="Adamnnan", ranking=46}}
RRIncData_Imported_Loot['Qiraji Bindings of Command']={{name="Veriia", ranking=50},{name="Placeholder", ranking=26},{name="Placeholder", ranking=26}}
RRIncData_Imported_Loot['Qiraji Bindings of Dominance']={{name="Placeholder", ranking=25},{name="Placeholder", ranking=25}}
RRIncData_Imported_Loot['Cloak of Concentrated Hatred']={{name="Teikoku", ranking=59},{name="Sicillian", ranking=59},{name="Nothagnus", ranking=54},{name="Galedia", ranking=52},{name="Hardcoore", ranking=41}}
RRIncData_Imported_Loot['Ring of Swarming Thought']={{name="Adamnnan", ranking=41},{name="Jolina", ranking=33}}
RRIncData_Imported_Loot['Cape of the Trinity']={{name="Magnor", ranking=46}}
RRIncData_Imported_Loot['Ternary Mantle']={{name="Thalindra", ranking=50}}
RRIncData_Imported_Loot['Ring of the Devoured']={{name="Hylea", ranking=48}}
RRIncData_Imported_Loot['Wand of Qiraji Nobility']={{name="Greenglare", ranking=49},{name="Laorra", ranking=46},{name="Pug", ranking=45},{name="Lazarus", ranking=44},{name="Magnor", ranking=42},{name="Adamnnan", ranking=41}}
RRIncData_Imported_Loot['Ukko\'s Ring of Darkness']={{name="Adamnnan", ranking=37}}
RRIncData_Imported_Loot['Badge of the Swarmguard']={{name="Yallfolx", ranking=60},{name="Harla", ranking=54},{name="Pudde", ranking=50},{name="Hardcoore", ranking=46},{name="Nothagnus", ranking=45},{name="Tuuf", ranking=42},{name="Firê", ranking=42}}
RRIncData_Imported_Loot['Gauntlets of Steadfast Determination']={{name="Cakey", ranking=37}}
RRIncData_Imported_Loot['Gloves of Enforcement']={{name="Stealthlink", ranking=53}}
RRIncData_Imported_Loot['Legplates of Blazing Light']={{name="Sieje", ranking=57}}
RRIncData_Imported_Loot['Sartura\'s Might']={{name="Koloblicino", ranking=58},{name="Laorra", ranking=58},{name="Veriia", ranking=52},{name="Zelen", ranking=50}}
RRIncData_Imported_Loot['Silithid Claw']={{name="Harla", ranking=52},{name="Pudde", ranking=49},{name="Hardcoore", ranking=41}}
RRIncData_Imported_Loot['Ancient Qiraji Ripper']={{name="Stabbycorvo", ranking=61},{name="Exeles", ranking=49},{name="Crit", ranking=44},{name="Firê", ranking=43}}
RRIncData_Imported_Loot['Barb of the Sand Reaver']={{name="Pudde", ranking=49},{name="Hardcoore", ranking=42}}
RRIncData_Imported_Loot['Barbed Choker']={{name="Crit", ranking=67},{name="Petarus", ranking=47},{name="Hardcoore", ranking=39}}
RRIncData_Imported_Loot['Robes of the Guardian Saint']={{name="Holycharge", ranking=57},{name="Secretary", ranking=56},{name="Koloblicino", ranking=55},{name="Veriia", ranking=54},{name="Laorra", ranking=52},{name="Thalindra", ranking=49},{name="Derpa", ranking=47}}
RRIncData_Imported_Loot['Silithid Carapace Chestguard']={{name="Crit", ranking=47}}
RRIncData_Imported_Loot['Libram of Grace']={{name="Mimse", ranking=45}}
RRIncData_Imported_Loot['Ring of the Qiraji Fury']={{name="Harla", ranking=56},{name="Sicillian", ranking=56},{name="Warlion", ranking=52},{name="Galedia", ranking=50},{name="Hardcoore", ranking=39}}
RRIncData_Imported_Loot['Scarab Brooch']={{name="Pervink", ranking=50},{name="Mimse", ranking=48},{name="Veriia", ranking=46},{name="Derpa", ranking=46}}
RRIncData_Imported_Loot['Sharpened Silithid Femur']={{name="Lazarus", ranking=54},{name="Greenglare", ranking=52},{name="Jolina", ranking=47},{name="Pug", ranking=46},{name="Mimse", ranking=45},{name="Ríku", ranking=45}}
RRIncData_Imported_Loot['Cloak of the Golden Hive']={{name="Cakey", ranking=37}}
RRIncData_Imported_Loot['Gloves of the Messiah']={{name="Koloblicino", ranking=54},{name="Laorra", ranking=45}}
RRIncData_Imported_Loot['Hive Defiler Wristguards']={{name="Galedia", ranking=47},{name="Crit", ranking=45},{name="Petarus", ranking=42},{name="Firê", ranking=38},{name="Cakey", ranking=32}}
RRIncData_Imported_Loot['Ring of the Martyr']={{name="Koloblicino", ranking=57},{name="Holycharge", ranking=55},{name="Veriia", ranking=51},{name="Mimse", ranking=51},{name="Derpa", ranking=50},{name="Zelen", ranking=49},{name="Sieje", ranking=39}}
RRIncData_Imported_Loot['Boots of Epiphany']={{name="Magnor", ranking=41},{name="Jolina", ranking=40}}
RRIncData_Imported_Loot['Royal Scepter of Vek\'lor']={{name="Adamnnan", ranking=52},{name="Greenglare", ranking=50},{name="Lazarus", ranking=49},{name="Pug", ranking=46}}
RRIncData_Imported_Loot['Ring of Emperor Vek\'lor']={{name="Mimse", ranking=42}}
RRIncData_Imported_Loot['Qiraji Execution Bracers']={{name="Latham", ranking=60},{name="Sicillian", ranking=58},{name="Stabbycorvo", ranking=57},{name="Galedia", ranking=53},{name="Secretary", ranking=51}}
RRIncData_Imported_Loot['Amulet of Vek\'nilash']={{name="Greenglare", ranking=51},{name="Pug", ranking=48},{name="Rusdor", ranking=48},{name="Sujjilad", ranking=38}}
RRIncData_Imported_Loot['Bracelets of Royal Redemption']={{name="Thalindra", ranking=54},{name="Pervink", ranking=54},{name="Veriia", ranking=50},{name="Derpa", ranking=50},{name="Celesta", ranking=48}}
RRIncData_Imported_Loot['Gloves of the Hidden Temple']={{name="Hylea", ranking=47}}
RRIncData_Imported_Loot['Kalimdor\'s Revenge']={{name="Yallfolx", ranking=39}}
RRIncData_Imported_Loot['Burrower\'s Bracers']={{name="Greenglare", ranking=49},{name="Magnor", ranking=44},{name="Jolina", ranking=42},{name="Drstomplol", ranking=32}}
RRIncData_Imported_Loot['Don Rigoberto\'s Lost Hat']={{name="Holycharge", ranking=61},{name="Derpa", ranking=49}}
RRIncData_Imported_Loot['Jom Gabbar']={{name="Teikoku", ranking=60},{name="Stabbycorvo", ranking=57},{name="Pudde", ranking=53},{name="Akiro", ranking=52},{name="Latham", ranking=50},{name="Nothagnus", ranking=46},{name="Petarus", ranking=45},{name="Yallfolx", ranking=41},{name="Cakey", ranking=33}}
RRIncData_Imported_Loot['Larvae of the Great Worm']={{name="Latham", ranking=57},{name="Warlion", ranking=56},{name="Crit", ranking=51},{name="Yallfolx", ranking=45}}
RRIncData_Imported_Loot['Ouro\'s Intact Hide']={{name="Stealthlink", ranking=71},{name="Magnor", ranking=64},{name="Laorra", ranking=58},{name="Cakey", ranking=35}}
RRIncData_Imported_Loot['Belt of Never-ending Agony']={{name="Stealthlink", ranking=62},{name="Exeles", ranking=62},{name="Teikoku", ranking=61},{name="Sicillian", ranking=55}}
RRIncData_Imported_Loot['Carapace of the Old God']={{name="Stealthlink", ranking=75}}
RRIncData_Imported_Loot['Cloak of Clarity']={{name="Zelen", ranking=60},{name="Thalindra", ranking=59},{name="Derpa", ranking=52},{name="Mimse", ranking=48},{name="Sieje", ranking=44}}
RRIncData_Imported_Loot['Cloak of the Devoured']={{name="Drstomplol", ranking=49},{name="Pug", ranking=47},{name="Greenglare", ranking=44},{name="Adamnnan", ranking=44},{name="Secretary", ranking=43}}
RRIncData_Imported_Loot['Dark Edge of Insanity']={{name="Nothagnus", ranking=59},{name="Galedia", ranking=49},{name="Warlion", ranking=48},{name="Yallfolx", ranking=45},{name="Cakey", ranking=43}}
RRIncData_Imported_Loot['Dark Storm Gauntlets']={{name="Rusdor", ranking=50},{name="Jolina", ranking=49},{name="Pug", ranking=49},{name="Ríku", ranking=47}}
RRIncData_Imported_Loot['Death\'s Sting']={{name="Exeles", ranking=61},{name="Valantha", ranking=58},{name="Galedia", ranking=46},{name="Stabbycorvo", ranking=43}}
RRIncData_Imported_Loot['Eye of C\'Thun']={{name="Harla", ranking=65},{name="Nothagnus", ranking=63},{name="Xygo", ranking=60},{name="Crit", ranking=59},{name="Galedia", ranking=59},{name="Pug", ranking=57},{name="Derpa", ranking=57},{name="Celesta", ranking=54},{name="Hardcoore", ranking=54},{name="Petarus", ranking=47},{name="Firê", ranking=43}}
RRIncData_Imported_Loot['Eyestalk Waist Cord']={{name="Lazarus", ranking=55},{name="Drstomplol", ranking=53},{name="Pug", ranking=52},{name="Rusdor", ranking=49},{name="Sujjilad", ranking=49},{name="Adamnnan", ranking=47},{name="Ríku", ranking=45},{name="Jolina", ranking=43}}
RRIncData_Imported_Loot['Gauntlets of Annihilation']={{name="Xygo", ranking=61},{name="Galedia", ranking=59},{name="Petarus", ranking=58},{name="Firê", ranking=52},{name="Nothagnus", ranking=51},{name="Secretary", ranking=47},{name="Sieje", ranking=46},{name="Crit", ranking=42},{name="Cakey", ranking=36}}
RRIncData_Imported_Loot['Grasp of the Old God']={{name="Pervink", ranking=59},{name="Derpa", ranking=56},{name="Celesta", ranking=46},{name="Mimse", ranking=46},{name="Sieje", ranking=43}}
RRIncData_Imported_Loot['Mark of C\'Thun']={{name="Petarus", ranking=41},{name="Cakey", ranking=36}}
RRIncData_Imported_Loot['Scepter of the False Prophet']={{name="Secretary", ranking=60},{name="Zelen", ranking=60},{name="Thalindra", ranking=59},{name="Koloblicino", ranking=58},{name="Veriia", ranking=57},{name="Sieje", ranking=54},{name="Laorra", ranking=48},{name="Linkiz", ranking=48}}
RRIncData_Imported_Loot['Vanquished Tentacle of C\'Thun']={{name="Mimse", ranking=43},{name="Greenglare", ranking=41},{name="Petarus", ranking=41},{name="Jolina", ranking=32}}
RRIncData_Imported_Loot['Ghoul Skin Tunic']={{name="Petarus", ranking=48},{name="Valantha", ranking=45}}
RRIncData_Imported_Loot['Belt of the Grand Crusader']={{name="Sieje", ranking=38}}
RRIncData_Imported_Loot['Pauldrons of the Grand Crusader']={{name="Holycharge", ranking=48}}
RRIncData_Imported_Loot['Harbinger of Doom']={{name="Valantha", ranking=47},{name="Hardcoore", ranking=46}}
RRIncData_Imported_Loot['Misplaced Servo Arm']={{name="Crit", ranking=53},{name="Yallfolx", ranking=44}}
RRIncData_Imported_Loot['Stygian Buckler']={{name="Petarus", ranking=44}}
RRIncData_Imported_Loot['Ring of the Eternal Flame']={{name="Sujjilad", ranking=45},{name="Rusdor", ranking=43},{name="Drstomplol", ranking=33}}
RRIncData_Imported_Loot['Desecrated Shoulderpads']={{name="Ríku", ranking=55},{name="Laorra", ranking=54},{name="Greenglare", ranking=47},{name="Adamnnan", ranking=42},{name="Rusdor", ranking=42},{name="Sujjilad", ranking=42},{name="Jolina", ranking=41},{name="Drstomplol", ranking=37}}
RRIncData_Imported_Loot['Desecrated Spaulders']={{name="Derpa", ranking=59},{name="Mimse", ranking=57},{name="Holycharge", ranking=56},{name="Akiro", ranking=52},{name="Hardcoore", ranking=49},{name="Linkiz", ranking=46},{name="Hylea", ranking=42},{name="Secretary", ranking=41}}
RRIncData_Imported_Loot['Desecrated Pauldrons']={{name="Teikoku", ranking=57},{name="Galedia", ranking=49},{name="Stabbycorvo", ranking=49},{name="Xygo", ranking=49},{name="Cakey", ranking=48},{name="Valantha", ranking=46},{name="Nothagnus", ranking=44},{name="Firê", ranking=42},{name="Tuuf", ranking=41},{name="Crit", ranking=39}}
RRIncData_Imported_Loot['Desecrated Bindings']={{name="Ríku", ranking=52},{name="Adamnnan", ranking=44},{name="Sujjilad", ranking=43},{name="Jolina", ranking=42},{name="Rusdor", ranking=42},{name="Thalindra", ranking=41}}
RRIncData_Imported_Loot['Desecrated Wristguards']={{name="Holycharge", ranking=56},{name="Akiro", ranking=48},{name="Hardcoore", ranking=47},{name="Linkiz", ranking=47},{name="Hylea", ranking=40},{name="Secretary", ranking=39}}
RRIncData_Imported_Loot['Desecrated Bracers']={{name="Xygo", ranking=53},{name="Stabbycorvo", ranking=52},{name="Latham", ranking=52},{name="Cakey", ranking=52},{name="Mondea", ranking=51},{name="Petarus", ranking=45},{name="Firê", ranking=39},{name="Tuuf", ranking=37}}
RRIncData_Imported_Loot['Desecrated Belt']={{name="Pervink", ranking=62},{name="Celesta", ranking=51},{name="Veriia", ranking=50},{name="Greenglare", ranking=49},{name="Ríku", ranking=49},{name="Sujjilad", ranking=44},{name="Thalindra", ranking=40},{name="Drstomplol", ranking=33}}
RRIncData_Imported_Loot['Desecrated Girdle']={{name="Hardcoore", ranking=51},{name="Akiro", ranking=51},{name="Hylea", ranking=42},{name="Secretary", ranking=41}}
RRIncData_Imported_Loot['Desecrated Waistguard']={{name="Teikoku", ranking=54},{name="Mondea", ranking=51},{name="Xygo", ranking=50},{name="Cakey", ranking=46},{name="Crit", ranking=45},{name="Valantha", ranking=44},{name="Firê", ranking=38}}
RRIncData_Imported_Loot['Desecrated Sandals']={{name="Pug", ranking=69},{name="Laorra", ranking=55},{name="Celesta", ranking=52},{name="Jolina", ranking=50},{name="Ríku", ranking=50},{name="Sujjilad", ranking=48},{name="Rusdor", ranking=46},{name="Adamnnan", ranking=45}}
RRIncData_Imported_Loot['Desecrated Boots']={{name="Derpa", ranking=61},{name="Zelen", ranking=50},{name="Hardcoore", ranking=49},{name="Akiro", ranking=49},{name="Linkiz", ranking=48},{name="Secretary", ranking=41},{name="Hylea", ranking=39}}
RRIncData_Imported_Loot['Desecrated Sabatons']={{name="Xygo", ranking=56},{name="Cakey", ranking=51},{name="Valantha", ranking=48},{name="Galedia", ranking=47},{name="Nothagnus", ranking=47},{name="Petarus", ranking=47},{name="Tuuf", ranking=42},{name="Firê", ranking=36}}
RRIncData_Imported_Loot['Band of Unanswered Prayers']={{name="Derpa", ranking=58},{name="Mimse", ranking=58},{name="Pervink", ranking=57},{name="Celesta", ranking=55},{name="Laorra", ranking=52},{name="Sieje", ranking=51},{name="Koloblicino", ranking=50},{name="Zelen", ranking=50},{name="Veriia", ranking=50},{name="Linkiz", ranking=49}}
RRIncData_Imported_Loot['Cryptfiend Silk Cloak']={{name="Hylea", ranking=54},{name="Crit", ranking=46}}
RRIncData_Imported_Loot['Gem of Nerubis']={{name="Adamnnan", ranking=35}}
RRIncData_Imported_Loot['Wristguards of Vengeance']={{name="Silverlane", ranking=56},{name="Petarus", ranking=56},{name="Xygo", ranking=55},{name="Yallfolx", ranking=55},{name="Mondea", ranking=53},{name="Valantha", ranking=49},{name="Nothagnus", ranking=48},{name="Derpa", ranking=45},{name="Sieje", ranking=44},{name="Cakey", ranking=44},{name="Crit", ranking=38},{name="Firê", ranking=38}}
RRIncData_Imported_Loot['The Widow\'s Embrace']={{name="Pervink", ranking=63},{name="Sieje", ranking=57},{name="Mimse", ranking=48},{name="Veriia", ranking=44},{name="Laorra", ranking=42}}
RRIncData_Imported_Loot['Widow\'s Remorse']={{name="Firê", ranking=50},{name="Nothagnus", ranking=40},{name="Crit", ranking=38}}
RRIncData_Imported_Loot['Desecrated Gloves']={{name="Ríku", ranking=52},{name="Laorra", ranking=51},{name="Greenglare", ranking=45},{name="Jolina", ranking=43},{name="Adamnnan", ranking=42},{name="Sujjilad", ranking=41},{name="Rusdor", ranking=38},{name="Drstomplol", ranking=34}}
RRIncData_Imported_Loot['Desecrated Handguards']={{name="Mimse", ranking=54},{name="Akiro", ranking=51},{name="Linkiz", ranking=46},{name="Hylea", ranking=42},{name="Secretary", ranking=40}}
RRIncData_Imported_Loot['Desecrated Gauntlets']={{name="Mondea", ranking=54},{name="Stabbycorvo", ranking=51},{name="Latham", ranking=51},{name="Xygo", ranking=51},{name="Cakey", ranking=48},{name="Crit", ranking=45},{name="Valantha", ranking=45},{name="Petarus", ranking=44},{name="Galedia", ranking=43},{name="Tuuf", ranking=41},{name="Firê", ranking=38}}
RRIncData_Imported_Loot['Kiss of the Spider']={{name="Stabbycorvo", ranking=60},{name="Petarus", ranking=60},{name="Crit", ranking=59},{name="Xygo", ranking=59},{name="Nothagnus", ranking=57},{name="Firê", ranking=55},{name="Latham", ranking=54},{name="Galedia", ranking=53},{name="Warlion", ranking=53},{name="Sicillian", ranking=53},{name="Cakey", ranking=52},{name="Tuuf", ranking=52},{name="Stealthlink", ranking=50},{name="Exeles", ranking=48},{name="Yallfolx", ranking=47},{name="Mondea", ranking=45}}
RRIncData_Imported_Loot['Maexxna\'s Fang']={{name="Galedia", ranking=44}}
RRIncData_Imported_Loot['Wraith Blade']={{name="Jolina", ranking=55},{name="Lazarus", ranking=55},{name="Adamnnan", ranking=55},{name="Rusdor", ranking=51},{name="Sujjilad", ranking=51},{name="Magnor", ranking=50},{name="Sieje", ranking=48}}
RRIncData_Imported_Loot['Band of the Inevitable']={{name="Adamnnan", ranking=46},{name="Jolina", ranking=41},{name="Sujjilad", ranking=37}}
RRIncData_Imported_Loot['Hatchet of Sundered Bone']={{name="Galedia", ranking=60},{name="Harla", ranking=60},{name="Pudde", ranking=53},{name="Sicillian", ranking=50},{name="Hardcoore", ranking=41}}
RRIncData_Imported_Loot['Noth\'s Frigid Heart']={{name="Holycharge", ranking=60},{name="Mimse", ranking=48},{name="Laorra", ranking=41}}
RRIncData_Imported_Loot['Libram of Light']={{name="Mimse", ranking=53},{name="Holycharge", ranking=51},{name="Secretary", ranking=48},{name="Derpa", ranking=46}}
RRIncData_Imported_Loot['Legplates of Carnage']={{name="Petarus", ranking=60},{name="Warlion", ranking=55},{name="Sicillian", ranking=55},{name="Mondea", ranking=55},{name="Nothagnus", ranking=49},{name="Firê", ranking=48},{name="Tuuf", ranking=44},{name="Cakey", ranking=41}}
RRIncData_Imported_Loot['Necklace of Necropsy']={{name="Derpa", ranking=58},{name="Mimse", ranking=55},{name="Laorra", ranking=44},{name="Secretary", ranking=39}}
RRIncData_Imported_Loot['Preceptor\'s Hat']={{name="Holycharge", ranking=53},{name="Sujjilad", ranking=38},{name="Jolina", ranking=34}}
RRIncData_Imported_Loot['Band of Unnatural Forces']={{name="Galedia", ranking=59},{name="Latham", ranking=59},{name="Mondea", ranking=59},{name="Exeles", ranking=58},{name="Warlion", ranking=57},{name="Hardcoore", ranking=57},{name="Xygo", ranking=55},{name="Stabbycorvo", ranking=53},{name="Sicillian", ranking=51},{name="Firê", ranking=51},{name="Valantha", ranking=50},{name="Nothagnus", ranking=49},{name="Tuuf", ranking=49},{name="Sieje", ranking=42},{name="Crit", ranking=41},{name="Cakey", ranking=38}}
RRIncData_Imported_Loot['Brimstone Staff']={{name="Magnor", ranking=58},{name="Jolina", ranking=37}}
RRIncData_Imported_Loot['Desecrated Leggings']={{name="Pug", ranking=59},{name="Adamnnan", ranking=50},{name="Laorra", ranking=50},{name="Celesta", ranking=50},{name="Ríku", ranking=49},{name="Greenglare", ranking=45},{name="Jolina", ranking=43},{name="Sujjilad", ranking=42},{name="Rusdor", ranking=37},{name="Drstomplol", ranking=35}}
RRIncData_Imported_Loot['Desecrated Legguards']={{name="Akiro", ranking=53},{name="Hardcoore", ranking=47},{name="Hylea", ranking=43}}
RRIncData_Imported_Loot['Desecrated Legplates']={{name="Teikoku", ranking=55},{name="Nothagnus", ranking=53},{name="Mondea", ranking=52},{name="Stabbycorvo", ranking=51},{name="Xygo", ranking=50},{name="Cakey", ranking=47},{name="Valantha", ranking=46},{name="Galedia", ranking=43},{name="Tuuf", ranking=40},{name="Firê", ranking=36}}
RRIncData_Imported_Loot['Ring of Spiritual Fervor']={{name="Magnor", ranking=45}}
RRIncData_Imported_Loot['The Eye of Nerub']={{name="Hardcoore", ranking=50},{name="Harla", ranking=49},{name="Pudde", ranking=46}}
RRIncData_Imported_Loot['Cloak of Suturing']={{name="Secretary", ranking=64},{name="Derpa", ranking=59},{name="Holycharge", ranking=58},{name="Mimse", ranking=58},{name="Pervink", ranking=54},{name="Celesta", ranking=53},{name="Veriia", ranking=50}}
RRIncData_Imported_Loot['Severance']={{name="Crit", ranking=37}}
RRIncData_Imported_Loot['The Plague Bearer']={{name="Cakey", ranking=42},{name="Petarus", ranking=39},{name="Nothagnus", ranking=38}}
RRIncData_Imported_Loot['Wand of Fates']={{name="Lazarus", ranking=46},{name="Jolina", ranking=43},{name="Adamnnan", ranking=43}}
RRIncData_Imported_Loot['The End of Dreams']={{name="Zelen", ranking=49},{name="Linkiz", ranking=39}}
RRIncData_Imported_Loot['Claymore of Unholy Might']={{name="Sieje", ranking=40}}
RRIncData_Imported_Loot['Death\'s Bargain']={{name="Mimse", ranking=43}}
RRIncData_Imported_Loot['Digested Hand of Power']={{name="Magnor", ranking=49}}
RRIncData_Imported_Loot['Gluth\'s Missing Collar']={{name="Sieje", ranking=43}}
RRIncData_Imported_Loot['Rime Covered Mantle']={{name="Magnor", ranking=52},{name="Sujjilad", ranking=49},{name="Jolina", ranking=48},{name="Rusdor", ranking=47},{name="Drstomplol", ranking=43}}
RRIncData_Imported_Loot['Desecrated Circlet']={{name="Greenglare", ranking=58},{name="Adamnnan", ranking=56},{name="Celesta", ranking=56},{name="Jolina", ranking=55},{name="Magnor", ranking=55},{name="Ríku", ranking=53},{name="Veriia", ranking=52},{name="Laorra", ranking=50},{name="Rusdor", ranking=46},{name="Sujjilad", ranking=46},{name="Drstomplol", ranking=44}}
RRIncData_Imported_Loot['Desecrated Headpiece']={{name="Derpa", ranking=65},{name="Zelen", ranking=49},{name="Akiro", ranking=47},{name="Hardcoore", ranking=44},{name="Hylea", ranking=43},{name="Secretary", ranking=40}}
RRIncData_Imported_Loot['Desecrated Helmet']={{name="Cakey", ranking=52},{name="Stabbycorvo", ranking=51},{name="Latham", ranking=51},{name="Petarus", ranking=51},{name="Galedia", ranking=50},{name="Mondea", ranking=50},{name="Valantha", ranking=47},{name="Xygo", ranking=46},{name="Firê", ranking=44},{name="Tuuf", ranking=43}}
RRIncData_Imported_Loot['Leggings of Polarity']={{name="Pug", ranking=58},{name="Greenglare", ranking=55},{name="Sujjilad", ranking=50},{name="Rusdor", ranking=45},{name="Drstomplol", ranking=43},{name="Adamnnan", ranking=40}}
RRIncData_Imported_Loot['Plated Abomination Ribcage']={{name="Yallfolx", ranking=57},{name="Mondea", ranking=56},{name="Warlion", ranking=54},{name="Petarus", ranking=53},{name="Xygo", ranking=52},{name="Nothagnus", ranking=49},{name="Firê", ranking=49},{name="Sicillian", ranking=47},{name="Tuuf", ranking=46},{name="Crit", ranking=41},{name="Cakey", ranking=36}}
RRIncData_Imported_Loot['Spire of Twilight']={{name="Laorra", ranking=46},{name="Thalindra", ranking=36}}
RRIncData_Imported_Loot['The Castigator']={{name="Petarus", ranking=50},{name="Firê", ranking=43},{name="Crit", ranking=38}}
RRIncData_Imported_Loot['Girdle of the Mentor']={{name="Galedia", ranking=61},{name="Valantha", ranking=57},{name="Warlion", ranking=57},{name="Mondea", ranking=56},{name="Petarus", ranking=56},{name="Xygo", ranking=55},{name="Crit", ranking=54},{name="Sicillian", ranking=52},{name="Yallfolx", ranking=50},{name="Cakey", ranking=50},{name="Firê", ranking=43},{name="Derpa", ranking=43},{name="Nothagnus", ranking=42},{name="Secretary", ranking=41},{name="Tuuf", ranking=41}}
RRIncData_Imported_Loot['Iblis, Blade of the Fallen Seraph']={{name="Hardcoore", ranking=55},{name="Petarus", ranking=54},{name="Teikoku", ranking=53},{name="Akiro", ranking=51},{name="Pudde", ranking=50},{name="Latham", ranking=46},{name="Firê", ranking=46},{name="Mondea", ranking=45},{name="Stabbycorvo", ranking=43}}
RRIncData_Imported_Loot['Signet of the Fallen Defender']={{name="Hylea", ranking=56}}
RRIncData_Imported_Loot['Wand of the Whispering Dead']={{name="Thalindra", ranking=52},{name="Celesta", ranking=52},{name="Koloblicino", ranking=51},{name="Laorra", ranking=51}}
RRIncData_Imported_Loot['Sadist\'s Collar']={{name="Sicillian", ranking=49},{name="Petarus", ranking=41}}
RRIncData_Imported_Loot['The Soul Harvester\'s Bindings']={{name="Drstomplol", ranking=49},{name="Magnor", ranking=49},{name="Jolina", ranking=46},{name="Sujjilad", ranking=42},{name="Rusdor", ranking=39}}
RRIncData_Imported_Loot['Corrupted Ashbringer']={{name="Silverlane", ranking=63},{name="Mondea", ranking=55},{name="Firê", ranking=53},{name="Mimse", ranking=53},{name="Xygo", ranking=52},{name="Secretary", ranking=49},{name="Yallfolx", ranking=49},{name="Petarus", ranking=49},{name="Derpa", ranking=42},{name="Cakey", ranking=40},{name="Sieje", ranking=37}}
RRIncData_Imported_Loot['Desecrated Breastplate']={{name="Stabbycorvo", ranking=53},{name="Valantha", ranking=52},{name="Petarus", ranking=52},{name="Cakey", ranking=50},{name="Galedia", ranking=48},{name="Tuuf", ranking=43},{name="Firê", ranking=43}}
RRIncData_Imported_Loot['Desecrated Robe']={{name="Greenglare", ranking=56},{name="Veriia", ranking=55},{name="Adamnnan", ranking=53},{name="Ríku", ranking=51},{name="Drstomplol", ranking=48},{name="Celesta", ranking=47},{name="Rusdor", ranking=46},{name="Sujjilad", ranking=46},{name="Jolina", ranking=45}}
RRIncData_Imported_Loot['Desecrated Tunic']={{name="Pudde", ranking=60},{name="Zelen", ranking=54},{name="Holycharge", ranking=53},{name="Secretary", ranking=51},{name="Hardcoore", ranking=50},{name="Akiro", ranking=50},{name="Linkiz", ranking=46},{name="Hylea", ranking=39}}
RRIncData_Imported_Loot['Seal of the Damned']={{name="Magnor", ranking=57},{name="Lazarus", ranking=46},{name="Drstomplol", ranking=40},{name="Sujjilad", ranking=37}}
RRIncData_Imported_Loot['Soulstring']={{name="Petarus", ranking=52},{name="Crit", ranking=51},{name="Sicillian", ranking=48},{name="Nothagnus", ranking=45},{name="Firê", ranking=45},{name="Xygo", ranking=44},{name="Cakey", ranking=41}}
RRIncData_Imported_Loot['Warmth of Forgiveness']={{name="Sieje", ranking=52},{name="Koloblicino", ranking=51},{name="Magnor", ranking=47},{name="Derpa", ranking=47},{name="Veriia", ranking=45}}
RRIncData_Imported_Loot['Claw of the Frost Wyrm']={{name="Hardcoore", ranking=47},{name="Pudde", ranking=46},{name="Cakey", ranking=38}}
RRIncData_Imported_Loot['Cloak of the Necropolis']={{name="Greenglare", ranking=57},{name="Adamnnan", ranking=52},{name="Lazarus", ranking=51},{name="Jolina", ranking=48},{name="Rusdor", ranking=47},{name="Sujjilad", ranking=43},{name="Drstomplol", ranking=41}}
RRIncData_Imported_Loot['Eye of the Dead']={{name="Derpa", ranking=61},{name="Mimse", ranking=60},{name="Zelen", ranking=56},{name="Laorra", ranking=56},{name="Sieje", ranking=56},{name="Holycharge", ranking=56},{name="Celesta", ranking=55},{name="Thalindra", ranking=53},{name="Pervink", ranking=52},{name="Linkiz", ranking=50},{name="Koloblicino", ranking=49},{name="Veriia", ranking=48}}
RRIncData_Imported_Loot['Glyph of Deflection']={{name="Nothagnus", ranking=42}}
RRIncData_Imported_Loot['Sapphiron\'s Left Eye']={{name="Adamnnan", ranking=54},{name="Jolina", ranking=51},{name="Magnor", ranking=50},{name="Lazarus", ranking=46},{name="Rusdor", ranking=46},{name="Sujjilad", ranking=46}}
RRIncData_Imported_Loot['Sapphiron\'s Right Eye']={{name="Secretary", ranking=60},{name="Mimse", ranking=60},{name="Veriia", ranking=56},{name="Koloblicino", ranking=52},{name="Celesta", ranking=52},{name="Thalindra", ranking=51},{name="Pervink", ranking=51},{name="Zelen", ranking=49},{name="Linkiz", ranking=45}}
RRIncData_Imported_Loot['Shroud of Dominion']={{name="Valantha", ranking=56},{name="Harla", ranking=56},{name="Silverlane", ranking=56},{name="Xygo", ranking=55},{name="Akiro", ranking=54},{name="Stealthlink", ranking=53},{name="Petarus", ranking=53},{name="Yallfolx", ranking=52},{name="Warlion", ranking=52},{name="Galedia", ranking=51},{name="Stabbycorvo", ranking=51},{name="Latham", ranking=51},{name="Hardcoore", ranking=50},{name="Sicillian", ranking=49},{name="Exeles", ranking=47},{name="Tuuf", ranking=46},{name="Firê", ranking=45},{name="Derpa", ranking=45},{name="Crit", ranking=37},{name="Cakey", ranking=35}}
RRIncData_Imported_Loot['Slayer\'s Crest']={{name="Harla", ranking=56},{name="Petarus", ranking=55},{name="Stabbycorvo", ranking=54},{name="Yallfolx", ranking=54},{name="Warlion", ranking=54},{name="Mondea", ranking=54},{name="Akiro", ranking=54},{name="Latham", ranking=52},{name="Hardcoore", ranking=52},{name="Valantha", ranking=47},{name="Nothagnus", ranking=46},{name="Sicillian", ranking=46},{name="Exeles", ranking=46},{name="Tuuf", ranking=43}}
RRIncData_Imported_Loot['The Face of Death']={{name="Crit", ranking=49},{name="Cakey", ranking=48},{name="Petarus", ranking=46},{name="Xygo", ranking=44},{name="Sicillian", ranking=44},{name="Mondea", ranking=44},{name="Nothagnus", ranking=41},{name="Valantha", ranking=40},{name="Tuuf", ranking=37},{name="Sieje", ranking=36}}
RRIncData_Imported_Loot['The Restrained Essence of Sapphiron']={{name="Magnor", ranking=60},{name="Pug", ranking=58},{name="Adamnnan", ranking=54},{name="Secretary", ranking=51},{name="Greenglare", ranking=51},{name="Jolina", ranking=51},{name="Lazarus", ranking=51},{name="Sujjilad", ranking=47},{name="Drstomplol", ranking=44},{name="Rusdor", ranking=40}}
RRIncData_Imported_Loot['Bonescythe Ring']={{name="Teikoku", ranking=58},{name="Miayunni", ranking=58},{name="Stabbycorvo", ranking=55},{name="Exeles", ranking=54},{name="Latham", ranking=46}}
RRIncData_Imported_Loot['Frostfire Ring']={{name="Sujjilad", ranking=52},{name="Rusdor", ranking=44},{name="Drstomplol", ranking=42}}
RRIncData_Imported_Loot['Plagueheart Ring']={{name="Pug", ranking=52}}
RRIncData_Imported_Loot['Ring of Faith']={{name="Veriia", ranking=55},{name="Thalindra", ranking=54}}
RRIncData_Imported_Loot['Ring of the Cryptstalker']={{name="Harla", ranking=52},{name="Akiro", ranking=48},{name="Hardcoore", ranking=45}}
RRIncData_Imported_Loot['Ring of the Dreadnaught']={{name="Nothagnus", ranking=54},{name="Crit", ranking=52},{name="Xygo", ranking=48},{name="Cakey", ranking=47},{name="Tuuf", ranking=36},{name="Firê", ranking=33}}
RRIncData_Imported_Loot['Ring of Redemption']={{name="Sieje", ranking=53},{name="Mimse", ranking=51},{name="Secretary", ranking=50},{name="Holycharge", ranking=49}}
RRIncData_Imported_Loot['Doomfinger']={{name="Adamnnan", ranking=51},{name="Lazarus", ranking=49},{name="Jolina", ranking=48},{name="Sujjilad", ranking=44},{name="Drstomplol", ranking=43},{name="Rusdor", ranking=43}}
RRIncData_Imported_Loot['Gem of Trapped Innocents']={{name="Secretary", ranking=58},{name="Mimse", ranking=58},{name="Pug", ranking=56},{name="Greenglare", ranking=54},{name="Magnor", ranking=53},{name="Jolina", ranking=49},{name="Lazarus", ranking=49},{name="Ríku", ranking=47},{name="Adamnnan", ranking=46},{name="Sujjilad", ranking=39},{name="Rusdor", ranking=38},{name="Drstomplol", ranking=36}}
RRIncData_Imported_Loot['Gressil, Dawn of Ruin']={{name="Stabbycorvo", ranking=63},{name="Warlion", ranking=63},{name="Stealthlink", ranking=63},{name="Miayunni", ranking=61},{name="Mondea", ranking=60},{name="Petarus", ranking=57},{name="Firê", ranking=55},{name="Valantha", ranking=53},{name="Exeles", ranking=52},{name="Teikoku", ranking=50},{name="Galedia", ranking=48},{name="Sicillian", ranking=47},{name="Xygo", ranking=43},{name="Nothagnus", ranking=40},{name="Cakey", ranking=33}}
RRIncData_Imported_Loot['Hammer of the Twisting Nether']={{name="Veriia", ranking=61},{name="Sieje", ranking=61},{name="Mimse", ranking=61},{name="Secretary", ranking=55},{name="Derpa", ranking=54},{name="Zelen", ranking=53},{name="Celesta", ranking=53},{name="Koloblicino", ranking=52},{name="Thalindra", ranking=51},{name="Pervink", ranking=51},{name="Linkiz", ranking=51}}
RRIncData_Imported_Loot['Kingsfall']={{name="Harla", ranking=62},{name="Exeles", ranking=54},{name="Pudde", ranking=53},{name="Akiro", ranking=52},{name="Galedia", ranking=45},{name="Hardcoore", ranking=44},{name="Stabbycorvo", ranking=42}}
RRIncData_Imported_Loot['Might of Menethil']={{name="Mondea", ranking=52},{name="Petarus", ranking=50},{name="Crit", ranking=49},{name="Yallfolx", ranking=49},{name="Galedia", ranking=47},{name="Sieje", ranking=47},{name="Cakey", ranking=37},{name="Tuuf", ranking=37}}
RRIncData_Imported_Loot['Nerubian Slavemaker']={{name="Pudde", ranking=63},{name="Warlion", ranking=56},{name="Hardcoore", ranking=56},{name="Akiro", ranking=56},{name="Yallfolx", ranking=53},{name="Stabbycorvo", ranking=52},{name="Petarus", ranking=51},{name="Stealthlink", ranking=48},{name="Valantha", ranking=46},{name="Latham", ranking=45},{name="Sicillian", ranking=45},{name="Tuuf", ranking=36}}
RRIncData_Imported_Loot['Shield of Condemnation']={{name="Holycharge", ranking=60},{name="Derpa", ranking=59},{name="Mimse", ranking=54},{name="Sieje", ranking=51}}
RRIncData_Imported_Loot['Soulseeker']={{name="Greenglare", ranking=53},{name="Sujjilad", ranking=49},{name="Adamnnan", ranking=45}}
RRIncData_Imported_Loot['Stormrage\'s Talisman of Seething']={{name="Warlion", ranking=58},{name="Miayunni", ranking=58},{name="Harla", ranking=56},{name="Petarus", ranking=53},{name="Galedia", ranking=52},{name="Valantha", ranking=51},{name="Hardcoore", ranking=51},{name="Mondea", ranking=50},{name="Nothagnus", ranking=49},{name="Yallfolx", ranking=49},{name="Hylea", ranking=47},{name="Tuuf", ranking=47},{name="Sicillian", ranking=45},{name="Cakey", ranking=34}}
RRIncData_Imported_Loot['The Hungering Cold']={{name="Valantha", ranking=63},{name="Petarus", ranking=61},{name="Nothagnus", ranking=60},{name="Yallfolx", ranking=58},{name="Warlion", ranking=58},{name="Mondea", ranking=58},{name="Xygo", ranking=57},{name="Galedia", ranking=55},{name="Stabbycorvo", ranking=53},{name="Miayunni", ranking=53},{name="Firê", ranking=53},{name="Tuuf", ranking=52},{name="Sicillian", ranking=51},{name="Cakey", ranking=51}}
RRIncData_Imported_Loot['The Phylactery of Kel\'Thuzad']={{name="Petarus", ranking=54},{name="Pudde", ranking=53},{name="Stealthlink", ranking=52},{name="Sieje", ranking=52},{name="Pervink", ranking=52},{name="Exeles", ranking=51},{name="Mondea", ranking=50},{name="Cakey", ranking=49},{name="Tuuf", ranking=49},{name="Nothagnus", ranking=48},{name="Latham", ranking=48},{name="Xygo", ranking=47},{name="Stabbycorvo", ranking=45},{name="Rusdor", ranking=38}}